### ISSUE TITLE
Dockerイメージにnpm がインストールされていない

### ISSUE THREAD

**Issue by yuki-toida** [shufo/docker-phoenix#2]
https://github.com/shufo/docker-phoenix/blob/master/Dockerfile#L13

上記に nodejs-npm を追記すればインストールされます。

もし権限をいただけるのでしたら、プルリクさせていただきます。
ご確認よろしくお願いいたします。

**Comment by shufo** [comment]
@yuki-toida 
Thank you for taking your time for the review!
紛らわしくて申し訳ないですがmasterの`1.4.5`等のイメージはproduction用に使いたいので今後nodejs消す予定です :bowing_man: というのはproductionで必要なランタイム以外を入れているとimageが重くなってデプロイサイクルが長くなるのと問題切り分けが難しくなるためです.

開発に必要なランタイムは`development`ブランチでタグを付けている`<version>-development`のタグの方に入れてlocal developmentは`<version>-development`で行っていこうと思っています。

もし開発にnpmが必要な場合は`<version>-development`タグのイメージに既に入っているのでそれを使ってもらえればと思います。

### example

```
docker run -it -w /code -v $(pwd):/code --entrypoint npm shufo/phoenix:1.4.5-development install
```

**Comment by yuki-toida** [comment]
なるほど！了解しました！
では、その方針で対応しますね。
ご返信いただきありがとうございます。
